v4l-sys/Cargo.toml, v4l2-sys/Cargo.toml
The new version of bindgen depends on LLVM/Clang libs in a way that is incompatible with previous bindgen versions.  As a result, one cannot depend on two different crates that use bindgen if one of them uses an older bindgen version.
=> Update to a newer version of bindgen

src/v4l2/vidioc.rs
Musl seems to use an int rather than an unsigned int for the args to the `ioctl` function as glibc does. This results in a compilation error when building with for example, `target = armv7-unknown-linux-musleabihf`
This patch changes the type alias to the correct type on musl crates. I imagine this might also be a problem on other libc implementations, but I'll leave those as they are since I can't test them.
=> Fix compilation error against musl

src/v4l2/api.rs
Annoyingly, the libc crate defines ioctl()'s argument types differently
on different platforms. On x86_64-unknown-linux-gnu, the existing code
works just fine. But, on aarch64-unknown-linux-musl (and Android
apparently), the libc crate instead says it takes an int, so we get a
compilation error.
We could work around this by writing the code differently for different
targets with #[cfg()]. But, that's less than ideal.
So, hack around this by using syscall() instead. It's a variadic
function, so we can just pass ~whatever~ into it. We're kind of
depending on C's type conversion rules by doing so, but this turns out
to be kind of how e.g. glibc does it anyway.
At the end of the day: this should "just work" on all targets.
Signed-off-by: Axel Rasmussen <axelrasmussen@google.com>
=> v4l2: api: Fix ioctl() argument type mismatch.

src/io/mmap/stream.rs, src/io/userptr/stream.rs
I had issues with my laptop not being able to capture as fast as I expected it would.
Even with the power setting on maximum performance it wasn't able to do 720p/30 MJPEG.
After some poking around I noticed that the user buffers weren't passed to v4l on initialization as you are supped to do.
Without enqueuing all unused buffers v4l have nowhere to store incoming frames until stream.next() is called which
enqueues one buffer.
This causes v4l to drop frames when stream.next() isn't called fast enough, i.e no time for any kind of processing of the images.
After this change my laptop have no  any issues capturing 720p/30 MJPEG, even in power saving mode.
=> Handover all buffers to v4l on stream start.

src/control.rs, src/device.rs
This adds a basic Extended controls support. The v4l2 API provides a way to write arrays of data that are here passed as Vec<T>.
=> Add support for ext ctrls

src/device.rs
On certain platforms, like when cross-compiling to Android, strings are defined as `u8` instead of `i8`.  The `c_char` type abstracts this detail away and is used in bindgen, and should hence be used in this cast too.
=> device: Cast string-pointer to c_char instead of i8

src/control.rs, src/device.rs, src/v4l2/vidioc.rs
Move away from the old VIDIOC_{G,S}_CTRL API.
The new API allows for larger data types (e.g. 64 bit integers) and
multi-dimensional controls.
Signed-off-by: Christopher N. Hesse <raymanfx@gmail.com>
=> control: Complete transition to VIDIOC_{G,S}_EXT_CTRLS API

Cargo.toml
The following warning shows while building:
warning: unused manifest key: workspaces
The correct spelling is `[workspace]`, without s: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspace-section
=> cargo: Include -sys crates in workspace by fixing plural typo

src/device.rs
Switch v4l2_ext_control string union cast to os::raw::c_char instead of i8 to match type used by bindgen generated code
For some targets, like armv7-unknown-linux-gnueabihf, the os c_char type is u8
and casting to i8 resulting in the following compilation error:
```
error[E0308]: mismatched types
--> src/device.rs:269:59
|
269 |                         control.__bindgen_anon_1.string = val.as_ptr() as *mut i8;
|                                                           ^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
|
= note: expected raw pointer `*mut u8`
found raw pointer `*mut i8`
```
=> Switch v4l2_ext_control string union cast to os::raw::c_char

.travis.yml, src/capability.rs, src/format/description.rs, src/frameinterval.rs, src/framesize.rs, src/lib.rs, src/v4l2/api.rs
Fix the broken intra-doc link to ioctl codes, and remove all units between brackets which are treated as links in markdown.  The CI now build-tests the documentation to prevent broken links and other issues in the future.  Aside that, improve the markdown style and fix a typo.
CC #47
=> Build-test documentation in Travis and fix intradoc links

src/device.rs
The v4l2_ctrls struct was unused (found after converting the assignments to a struct initializer, expect a bigger PR for that later), and v4l2_ctrl was erroneously passed as pointer argument to VIDIOC_G_EXT_CTRLS.
Also use the newer style of `.cast()` to perform raw pointer casts with coercion, to appease rusts (currently default-allowed, though) `trivial_casts` lint.
Fixes: 99ebd12 ("control: Complete transition to VIDIOC_{G,S}_EXT_CTRLS API (#41)")
=> device: Use ctrls instead of ctrl structure in VIDIOC_G_EXT_CTRLS

src/control.rs, src/device.rs, src/format/mod.rs, src/fraction.rs, src/io/mmap/arena.rs, src/io/mmap/stream.rs, src/io/userptr/arena.rs, src/io/userptr/stream.rs, src/timestamp.rs, src/video/capture/mod.rs, src/video/capture/parameters.rs, src/video/macros.rs, src/video/output/mod.rs, src/video/output/parameters.rs
The main advantages are:
- More readable as the variable name of the struct need not be repeated;
- `mem::zeroed()` can be dropped (there is a lint for this) if all members are initialized;
- Sometimes `mut` can be dropped, as no variables are updated anymore after initialization;
- Helped the linter uncover an "unused variable" that turned out to be a bug (wrong local variable was used: #52), which it is strangely not able to find for mutable structs that are only ever initialized and updated, but never read.
Downsides:
- Some apparently find the syntax "ugly", in particular around FFI contexts?
- Depending on the context, takes 1-2 more lines of code;
- This PR contains some semantic changes where a simple field update of ie. `.index` is replaced with a re-initialization of the entire …
=> Use struct initializers instead of member initializers over zeroed data

src/format/fourcc.rs
- fourcc: Fix `clippy::needless_late_init`
- fourcc: Simplify
- fourcc: Simplify further with `to/from_le_bytes`
=> fourcc: Fix `clippy::needless_late_init` and simplify with `to/from_le_bytes()`

src/device.rs, src/io/mmap/stream.rs, src/io/userptr/stream.rs, src/lib.rs, src/pselect.rs
This resolves #16.
Additionally, are you interested in supporting a `timeout` for polling the frames? Using `pselect` this is doable now.
=> Don't block when unplugging camera

src/context.rs, src/control.rs
Address some new linter warnings through cleanup, that are preventing other PRs from making it in.
=> Run `cargo clippy --fix` on Rust 1.63

src/device.rs
I had a issue while parsing for a value presented as i32 instead of i64. 
(basically one of my laptop's camera brightness goes from -64 to 64 and that caused a panic anytime I'd set it to a negative number)
Should every case be handled differently?  for now, just adjusted it for my own needs.
PS: thanks a lot for the library! =)
=> controls: i32 separate handling

README.md
Actually print the format in use when saying so instead of printing the requested format.
=> Really print the format in use in Readme

Cargo.toml, src/buffer.rs, src/capability.rs, src/control.rs, src/format/description.rs, src/format/mod.rs, src/parameters.rs, src/v4l2/api.rs, src/video/capture/parameters.rs
CI throws an `clippy::bad_bit_mask` that has been fixed in `bitflags 2` [1], and it is always a good idea to stay up to date with the latest crate releases.
The major change is an internal restructuring into _two_ types, that require the user to now re-expose default traits implemented on the inner type to the outer type by `#[derive]`'ing them.
[1]: https://github.com/bitflags/bitflags/pull/373
---
On the side I'm not super happy with the `From` implementations using `from_bits_truncate()` to be lossy, in case the kernel adds newer values that we haven't yet mapped as constants: can we separately switch to `from_bits_retain()`?
=> Upgrade to `bitflags 2`

src/buffer.rs, src/capability.rs, src/control.rs, src/format/description.rs, src/format/mod.rs, src/parameters.rs, src/video/capture/parameters.rs
Depends on #79
`bitflags` intrinsically supports holding unknown flag values, and pretty-printing a non-zero hex code if there are any.  This should make our conversion functions lossless and allow us/users to more easily spot new, unsupported constants.
=> Retain instead of truncate unknown flags when converting to `bitflags`

.github/dependabot.yml
Let dependabot suggest dependency upgrades in `Cargo.toml` and the GitHub Actions CI scripts so that we don't forget / miss out on them.
=> Add dependabot configuration to GitHub CI

.github/workflows/ci.yml
The `actions-rs` containers haven't been maintained and updated for years and don't need to: GitHub's actions environment already comes fully loaded with a complete stable Rust installation with the standard tools (clippy, rustfmt, rustdoc).  Simple `run:` commands relate directly to what a developer can type in locally to "reproduce" the CI environment while they might be following up on CI failures, and no longer spam ancient Node 12 deprecation warnings.
The only downside is that `actions-rs` properly embeds build failures as code annotations in the diff.
=> CI: Replace deprecated/unmaintained `actions-rs` with simple `run:` steps

src/control.rs
Fixes #98
Draft change to make conversion from `v4l2_query_ext_ctrl` to `Description` - and within it `u32` to a `Type` - fallible rather than panicking on unknown type values.
This approach includes a few breaking changes, to store the unknown type in the struct.  Alternatively we could make the entire conversion for `v4l2_query_ext_ctrl` fallible via `TryFrom`?
=> control: Add `Type::Unknown`

src/v4l2/api.rs, src/v4l2/vidioc.rs, v4l2-sys/Cargo.toml, v4l2-sys/build.rs
I've used the proposed changes on a recent `FreeBSD CURRENT` with `amd64` (i.e. `x86_64`) architecture with `Logitech C922 Pro` webcam.
What works:
- video stream capturing via `MmapStream`
- querying and changing capturing formats
- querying and altering camera controls
What doesn't work:
- video stream capturing via `UserptrStream`
=> Add FreeBSD support

src/device.rs
As per https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/vidioc-g-ext-ctrls.html info, the __u32 size field should be set at zero value for immediate data types (i32, i64 and bool, which are all embedded into an i64 container), as any nonzero value will identify a pointer usage of the union. Tested on x86_64 and aarch64.
=> Fixed wrong size field in VIDIOC_S_EXT_CTRLS ioctl

src/buffer.rs
This is a teeny tiny change to fix the spelling for the `VbiCaputre` variant in the `buffer::Type` enum. Note that a major version bump is required to avoid violating semantic versioning.
=> BREAKING CHANGE: Spelling Fix for `Type::VbiCaputre`
